name: Bug
description: Reportar defeito reproduzível
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Como reproduzir
      description: Passos objetivos.
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      options:
        - local
        - staging
        - production
    validations:
      required: true
